name: segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - ansiwrap=0.8.4=py_0
  - appdirs=1.4.3=py_1
  - async_generator=1.10=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - black=19.10b0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.4=pyh9f0ad1d_0
  - brotlipy=0.7.0=py36h8c4c3a4_1000
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.14.0=py36hd463f26_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - click=7.1.1=pyh8c360ce_0
  - cloudpickle=1.3.0=py_0
  - cryptography=2.8=py36h45558ae_2
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.14.0=py_0
  - dataclasses=0.7=py36_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - freetype=2.10.1=he06d7ca_0
  - icu=58.2=hf484d3e_1000
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - importlib-metadata=1.6.0=py36h9f0ad1d_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.0=166
  - ipykernel=5.2.0=py36h95af2a2_1
  - ipython=7.13.0=py36h9f0ad1d_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py36h9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - jupyterlab=2.1.0=py_0
  - jupyterlab_server=1.1.1=py_0
  - kiwisolver=1.2.0=py36hdb11119_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libpng=1.6.37=hed695b0_1
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - lz4-c=1.9.2=he1b5a44_0
  - markupsafe=1.1.1=py36h8c4c3a4_1
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h8c4c3a4_1001
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.1=py36h830a2c2_0
  - mypy_extensions=0.4.3=py36h9f0ad1d_1
  - nbclient=0.2.0=py_0
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_0
  - nest-asyncio=1.3.2=py_0
  - networkx=2.4=py_1
  - ninja=1.10.0=hc9558a2_0
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.3=py36h830a2c2_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - papermill=2.1.0=py36h9f0ad1d_0
  - parso=0.7.0=pyh9f0ad1d_0
  - pathspec=0.8.0=pyh9f0ad1d_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py36_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0=py36h8c4c3a4_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10=hcf32534_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.3.1=cuda100py36h53c1284_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h785e9b2_1
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - pyzmq=19.0.0=py36h9947dbf_1
  - readline=8.0=h7b6447c_0
  - regex=2020.4.4=py36h8c4c3a4_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-image=0.16.2=py36hb3f55d8_0
  - scikit-learn=0.22.2.post1=py36hcdab131_0
  - scipy=1.4.1=py36h0b6359f_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py36_0
  - six=1.14.0=py_1
  - sqlite=3.31.1=h7b6447c_0
  - tenacity=6.1.0=py36h9f0ad1d_1
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - textwrap3=0.9.2=py_0
  - tk=8.6.8=hbc83047_0
  - toml=0.10.0=py_0
  - toolz=0.10.0=py_0
  - torchvision=0.4.2=cuda100py36hecfc37a_0
  - tornado=6.0.4=py36h8c4c3a4_1
  - tqdm=4.45.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typed-ast=1.4.1=py36h516909a_0
  - typing_extensions=3.7.4.1=py36h9f0ad1d_3
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.4=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h6597ccf_3

